#!/usr/bin/env bash

## Get data
STATUS="$(playerctl status)"

## Get status
get_status() {
  if [[ $STATUS == "Playing" ]]; then
    echo ""
  else
    echo "喇"
  fi
}

## Get song
get_song() {
  song=$(playerctl metadata --format '{{title}}')
  if [[ -z "$song" ]]; then
    echo "Offline"
  else
    echo "$song"
  fi
}

## Get artist
get_artist() {
  artist=$(playerctl metadata --format '{{artist}}')
  if [[ -z "$artist" ]]; then
    echo "Offline"
  else
    echo "$artist"
  fi
}

## Get time
get_time() {
  time=$(playerctl position | tr -d '(%)')
  if [[ -z "$time" ]]; then
    echo "0"
  else
    echo "$time"
  fi
}

## Get cover
get_cover() {
  curl -o /tmp/cover.png "$(playerctl metadata --format '{{mpris:artUrl}}')" &>/dev/null
  STATUS=$?

  # Check if the file has a embbeded album art
  if [ "$STATUS" -eq 0 ]; then
    echo "/tmp/cover.png"
  else
    echo "images/music.png"
  fi
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
  get_song
elif [[ "$1" == "--artist" ]]; then
  get_artist
elif [[ "$1" == "--status" ]]; then
  get_status
elif [[ "$1" == "--time" ]]; then
  get_time
elif [[ "$1" == "--cover" ]]; then
  get_cover
elif [[ "$1" == "--toggle" ]]; then
  playerctl play-pause
elif [[ "$1" == "--next" ]]; then
  {
    playerctl next
    get_cover
  }
elif [[ "$1" == "--prev" ]]; then
  {
    playerctl previous
    get_cover
  }
fi
